# ClusterImagePolicy: chỉ cho phép image từ ghcr.io/kaphudong đã được ký bằng cosign
# Áp cho namespace có label: policy.sigstore.dev/include=true
# QUAN TRỌNG: gắn label cho ns SAU khi image đã ký, gắn trước sẽ chặn luôn app-api
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-cosign-signature
spec:
  images:
  - glob: "ghcr.io/kaphudong/w10-api*"
  authorities:
  - key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWSkxk8UCgWLOOlDZQ6jdsSWaqFUp
        rBuCt0Bcr8qdgJQapMJypB5EdlaFqj5oe0Wo0RH6+DV3EmeyinVgrqzpeA==
        -----END PUBLIC KEY-----
