# Constraint: Bắt buộc có label 'owner' (Lab 1.3 - Custom Policy)
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireOwnerLabel
metadata:
  name: require-owner-label
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    - apiGroups: ["argoproj.io"]
      kinds: ["Rollout"]
    namespaces:
      - demo
  parameters:
    labels:
      - "owner"
