# Constraint: Bắt buộc có resources.limits (F-02)
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireResourceLimit
metadata:
  name: require-resource-limits
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
      - demo
