# Namespace: Tao namespace demo cho API workload
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    # Lab 2.2: enable Sigstore Policy Controller de verify cosign signature
    # Image da duoc ky trong CI -> an toan de enable
    policy.sigstore.dev/include: "true"
